#!/usr/bin/env python3
"""
analyze_usage.py
────────────────
Analyzes usage JSON files generated by the enhanced LLM client.
Provides insights into token consumption, costs, and tool usage patterns.

Usage:
  python scripts/analyze_usage.py <app-name>
  python scripts/analyze_usage.py <app-name> --detailed
  python scripts/analyze_usage.py --all
"""
import json
import sys
from pathlib import Path
from typing import Any
from datetime import datetime
from collections import defaultdict

import click
from rich.console import Console
from rich.table import Table
from rich import box

# Assuming script is in scripts/ and outputs/ is at repo root
REPO_ROOT = Path(__file__).parent.parent
OUTPUTS_DIR = REPO_ROOT / "outputs"

console = Console()


def load_usage_files(app_name: str | None = None) -> list[dict[str, Any]]:
    """Load all usage JSON files for an app (or all apps)."""
    usage_files = []

    if app_name:
        usage_dir = OUTPUTS_DIR / app_name / "usage"
        if not usage_dir.exists():
            console.print(f"[red]❌ No usage directory found for app: {app_name}[/red]")
            return []
        pattern = usage_dir.glob("usage_*.json")
    else:
        pattern = OUTPUTS_DIR.glob("*/usage/usage_*.json")

    for file_path in pattern:
        try:
            data = json.loads(file_path.read_text())
            data["_file_path"] = str(file_path)
            usage_files.append(data)
        except Exception as e:
            console.print(f"[yellow]⚠️  Error reading {file_path}: {e}[/yellow]")

    return sorted(usage_files, key=lambda x: x.get("start_time", ""))


def format_timestamp(iso_str: str) -> str:
    """Format ISO timestamp to readable string."""
    try:
        dt = datetime.fromisoformat(iso_str.replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d %H:%M:%S")
    except Exception:
        return iso_str


def analyze_summary(usage_files: list[dict[str, Any]]) -> None:
    """Print aggregate summary statistics."""
    if not usage_files:
        console.print("[yellow]No usage files found.[/yellow]")
        return

    total_executions = len(usage_files)
    total_cost = sum(f["summary"]["total_cost_usd"] for f in usage_files)
    total_tokens = sum(f["summary"]["total_tokens"] for f in usage_files)
    total_input_tokens = sum(f["summary"]["total_input_tokens"] for f in usage_files)
    total_output_tokens = sum(f["summary"]["total_output_tokens"] for f in usage_files)
    total_cache_read = sum(f["summary"]["total_cache_read_tokens"] for f in usage_files)
    total_llm_calls = sum(f["summary"]["total_llm_calls"] for f in usage_files)
    total_tool_uses = sum(f["summary"]["total_tool_uses"] for f in usage_files)

    # Calculate cache hit rate
    cache_eligible = total_input_tokens
    cache_hit_rate = (total_cache_read / cache_eligible * 100) if cache_eligible > 0 else 0

    console.print("\n[bold cyan]📊 Aggregate Summary[/bold cyan]\n")

    table = Table(box=box.SIMPLE)
    table.add_column("Metric", style="cyan")
    table.add_column("Value", style="yellow", justify="right")

    table.add_row("Total Executions", str(total_executions))
    table.add_row("Total Cost", f"${total_cost:.4f}")
    table.add_row("Avg Cost/Execution", f"${total_cost/total_executions:.4f}")
    table.add_row("", "")
    table.add_row("Total Tokens", f"{total_tokens:,}")
    table.add_row("  ├─ Input Tokens", f"{total_input_tokens:,}")
    table.add_row("  ├─ Output Tokens", f"{total_output_tokens:,}")
    table.add_row("  └─ Cache Read", f"{total_cache_read:,}")
    table.add_row("Cache Hit Rate", f"{cache_hit_rate:.1f}%")
    table.add_row("", "")
    table.add_row("Total LLM Calls", str(total_llm_calls))
    table.add_row("Total Tool Uses", str(total_tool_uses))

    console.print(table)


def analyze_by_command(usage_files: list[dict[str, Any]]) -> None:
    """Break down stats by command."""
    by_command: dict[str, dict[str, Any]] = defaultdict(lambda: {
        "count": 0,
        "cost": 0.0,
        "tokens": 0,
        "tool_uses": 0,
    })

    for file in usage_files:
        cmd = file.get("command", "unknown")
        summary = file["summary"]
        by_command[cmd]["count"] += 1
        by_command[cmd]["cost"] += summary["total_cost_usd"]
        by_command[cmd]["tokens"] += summary["total_tokens"]
        by_command[cmd]["tool_uses"] += summary["total_tool_uses"]

    console.print("\n[bold cyan]📋 By Command[/bold cyan]\n")

    table = Table(box=box.ROUNDED)
    table.add_column("Command", style="cyan")
    table.add_column("Runs", justify="right")
    table.add_column("Total Cost", justify="right")
    table.add_column("Avg Cost", justify="right")
    table.add_column("Tokens", justify="right")
    table.add_column("Tools", justify="right")

    for cmd, stats in sorted(by_command.items()):
        table.add_row(
            cmd,
            str(stats["count"]),
            f"${stats['cost']:.4f}",
            f"${stats['cost']/stats['count']:.4f}",
            f"{stats['tokens']:,}",
            str(stats["tool_uses"]),
        )

    console.print(table)


def analyze_tool_usage(usage_files: list[dict[str, Any]]) -> None:
    """Analyze which tools are used most frequently."""
    tool_counts: dict[str, int] = defaultdict(int)

    for file in usage_files:
        for tool_use in file.get("tool_uses", []):
            tool_name = tool_use.get("tool_name", "unknown")
            tool_counts[tool_name] += 1

    if not tool_counts:
        console.print("\n[yellow]No tool usage recorded.[/yellow]")
        return

    console.print("\n[bold cyan]🔧 Tool Usage Frequency[/bold cyan]\n")

    table = Table(box=box.ROUNDED)
    table.add_column("Tool", style="cyan")
    table.add_column("Uses", justify="right", style="yellow")
    table.add_column("% of Total", justify="right", style="dim")

    total_uses = sum(tool_counts.values())

    for tool, count in sorted(tool_counts.items(), key=lambda x: x[1], reverse=True):
        percentage = (count / total_uses * 100) if total_uses > 0 else 0
        table.add_row(tool, str(count), f"{percentage:.1f}%")

    console.print(table)


def show_detailed_list(usage_files: list[dict[str, Any]]) -> None:
    """Show detailed list of all executions."""
    console.print("\n[bold cyan]📄 Detailed Execution List[/bold cyan]\n")

    table = Table(box=box.ROUNDED, show_lines=True)
    table.add_column("Date", style="dim")
    table.add_column("App", style="cyan")
    table.add_column("Command", style="yellow")
    table.add_column("Turns", justify="right")
    table.add_column("Tools", justify="right")
    table.add_column("Tokens", justify="right")
    table.add_column("Cost", justify="right", style="green")

    for file in usage_files:
        summary = file["summary"]
        table.add_row(
            format_timestamp(file.get("start_time", "")),
            file.get("app_name", "?"),
            file.get("command", "?"),
            str(summary.get("total_turns", 0)),
            str(summary.get("total_tool_uses", 0)),
            f"{summary.get('total_tokens', 0):,}",
            f"${summary.get('total_cost_usd', 0.0):.4f}",
        )

    console.print(table)


def analyze_cost_trends(usage_files: list[dict[str, Any]]) -> None:
    """Show cost trends over time."""
    if len(usage_files) < 2:
        return

    console.print("\n[bold cyan]📈 Cost Trends[/bold cyan]\n")

    # Group by date
    by_date: dict[str, dict[str, Any]] = defaultdict(lambda: {
        "cost": 0.0,
        "tokens": 0,
        "count": 0,
    })

    for file in usage_files:
        date_str = file.get("start_time", "")[:10]  # YYYY-MM-DD
        summary = file["summary"]
        by_date[date_str]["cost"] += summary["total_cost_usd"]
        by_date[date_str]["tokens"] += summary["total_tokens"]
        by_date[date_str]["count"] += 1

    table = Table(box=box.ROUNDED)
    table.add_column("Date", style="cyan")
    table.add_column("Runs", justify="right")
    table.add_column("Daily Cost", justify="right", style="green")
    table.add_column("Tokens", justify="right")

    for date, stats in sorted(by_date.items()):
        table.add_row(
            date,
            str(stats["count"]),
            f"${stats['cost']:.4f}",
            f"{stats['tokens']:,}",
        )

    console.print(table)


@click.command()
@click.argument("app_name", required=False)
@click.option("--detailed", "-d", is_flag=True, help="Show detailed execution list")
@click.option("--all", "-a", "all_apps", is_flag=True, help="Analyze all apps")
def main(app_name: str | None, detailed: bool, all_apps: bool):
    """Analyze LLM usage statistics from JSON files."""

    if all_apps:
        app_name = None
        console.print("[bold]Analyzing all applications...[/bold]")
    elif app_name:
        console.print(f"[bold]Analyzing application: {app_name}[/bold]")
    else:
        console.print("[red]❌ Please specify an app name or use --all[/red]")
        console.print("\nUsage:")
        console.print("  python scripts/analyze_usage.py <app-name>")
        console.print("  python scripts/analyze_usage.py --all")
        sys.exit(1)

    usage_files = load_usage_files(app_name)

    if not usage_files:
        console.print("\n[yellow]No usage data found.[/yellow]")
        sys.exit(0)

    console.print(f"\n[dim]Loaded {len(usage_files)} execution records[/dim]")

    # Show analyses
    analyze_summary(usage_files)
    analyze_by_command(usage_files)
    analyze_tool_usage(usage_files)
    analyze_cost_trends(usage_files)

    if detailed:
        show_detailed_list(usage_files)

    console.print("\n[dim]💡 Tip: Use --detailed for a full execution list[/dim]\n")


if __name__ == "__main__":
    main()
